import { supabase } from '@/lib/supabase'
import {
  getPendingScans,
  markScanSynced,
  markScanConflict,
  clearSyncedScans,
} from './db'
import type { SyncResult } from '@/types'

/**
 * Sync all pending offline scans to Supabase.
 * Handles conflicts: if a ticket was already used by another device,
 * marks the entry as 'conflict' for admin review.
 */
export async function syncOfflineScans(): Promise<SyncResult> {
  const pending = await getPendingScans()
  const result: SyncResult = { synced: 0, conflicts: 0, errors: 0 }

  for (const entry of pending) {
    try {
      // Check current ticket status
      const { data: ticket, error: fetchError } = await supabase
        .from('tickets')
        .select('id, status, used_at, used_by')
        .eq('id', entry.ticket_id)
        .single<{ id: string; status: string; used_at: string | null; used_by: string | null }>()

      if (fetchError || !ticket) {
        result.errors++
        continue
      }

      // Conflict: ticket was already used by someone else
      if (ticket.status === 'used' && ticket.used_by !== entry.staff_id) {
        await markScanConflict(entry.id)
        result.conflicts++
        continue
      }

      // Mark ticket as used (cast to any — proper types generated by Supabase CLI in M2)
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const ticketsTable = supabase.from('tickets') as any
      const { error: updateError } = await ticketsTable
        .update({
          status: 'used',
          used_at: entry.scanned_at,
          used_by: entry.staff_id,
        })
        .eq('id', entry.ticket_id)
        .eq('status', 'active') // optimistic lock — only update if still active

      if (updateError) {
        result.errors++
        continue
      }

      // Insert scan log
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      await (supabase.from('scan_logs') as any).insert({
        ticket_id: entry.ticket_id,
        staff_id: entry.staff_id,
        scanned_at: entry.scanned_at,
        device_id: entry.device_id,
        offline_flag: true,
        synced_at: new Date().toISOString(),
      })

      await markScanSynced(entry.id)
      result.synced++
    } catch {
      result.errors++
    }
  }

  // Clean up synced entries
  await clearSyncedScans()

  return result
}

/**
 * Listen for network recovery and auto-sync.
 */
export function registerSyncOnReconnect(
  onSync?: (result: SyncResult) => void
): () => void {
  const handler = async () => {
    const result = await syncOfflineScans()
    onSync?.(result)
  }

  window.addEventListener('online', handler)
  return () => window.removeEventListener('online', handler)
}
